# Generated by Django 5.2.3 on 2025-06-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemcommande',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
